///
/// \class gdw_panel gdw_panel.h
///
/// \brief Provides ...
///
/// This class handles ...
/// 

#include <wx/wxprec.h>

#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

#include <wx/treectrl.h>

#include <string>
#include "gdw_panel.h"



////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// \brief Constructor
///
/// The constructor ...
///
////////////////////////////////////////////////////////////////////////////////////////////////////



gdw_panel::gdw_panel(wxWindow *parent) : wxPanel(parent)
{
        std::cout << "gdw_panel Constructor: Start" << std::endl;

        CallAfter (&gdw_panel::delayed_start);
}

////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// \brief Run derived class startup method
///
/// The member function ...
///
////////////////////////////////////////////////////////////////////////////////////////////////////


void gdw_panel::delayed_start()
{
        try
        {
                process_window_draw();
        }
	catch (std::runtime_error& exception)
	{
                process_runtime_error (exception);
	}
	catch (std::logic_error& exception)
	{
                process_logic_error (exception);
	}
}





gdw_panel::~gdw_panel()
{
        std::cout << "gdw_panel Destructor Start" << std::endl;
}


////////////////////////////////////////////////////////////////////////////////////////////////////
///
/// \brief Event handler
///
/// This member function handles all of the wxWidgets events that are generated by TopFrame.
///
////////////////////////////////////////////////////////////////////////////////////////////////////


void gdw_panel::event_handler (wxEvent& event)
{
        try
        {
                process_window_events (&event);
        }
	catch (std::runtime_error& exception)
	{
                process_runtime_error (exception);
	}
	catch (std::logic_error& exception)
	{
                process_logic_error (exception);
	}

}



////////////////////////////////////////////////////////////////////////////////////////////////////
//
// Process a runtime error. Report the error message in a popup window
// (a modal dialogue), but it should be safe to carry on.
//
////////////////////////////////////////////////////////////////////////////////////////////////////

void gdw_panel::process_runtime_error (std::runtime_error& exception)
{
        wxString error_msg = exception.what();
        wxMessageDialog* msg_dia = new wxMessageDialog(NULL, error_msg, "Runtime Error");
        msg_dia->ShowModal();
}



////////////////////////////////////////////////////////////////////////////////////////////////////
//
// Process a program logic error (a bug). Report the error message in a popup window
// (a modal dialogue) and then terminate the program.
//
////////////////////////////////////////////////////////////////////////////////////////////////////

void gdw_panel::process_logic_error (std::logic_error& exception)
{
        // Generate a popup window (a modal dialogue) with the error message.
                
        wxString error_msg = exception.what();
        wxMessageDialog* msg_dia = new wxMessageDialog(NULL, error_msg, "Program Logic Error");
        msg_dia->ShowModal();

        // After the user closes the error window, safely close out the program.

        wxApp*    my_wxApp = wxTheApp;
        wxWindow* my_TopWindow = my_wxApp->GetTopWindow();
        my_TopWindow->Close();
}
